apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-lc-helloworld
spec:
  title: Hello from Eknath
  description: Workshop created to demo the workload creation in TKG
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Eknathreddy09/lab-lc-helloworld
  content:
     files: github.com/Eknathreddy09/lab-lc-helloworld:main
    #image: quay.io/eduk8s/lab-markdown-sample:master
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
